# github workflow to build and update docker service
# This workflow is triggered on push to the main branch
# and on pull request to the main branch
# It builds the docker image and pushes it to the docker registry
# It also deploys the docker image to the server

name: Build and Deploy Docker Service
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Deploy to server
      # uses docker service update
        run: |
            docker service update --image ${{ vars.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE }}:${{ github.sha }} ${{ vars.SERVICE_NAME }}
      
